branches:
  only:
    - master

language: go

script-anchors:
  - &script-linux-coverage
    - cd $TRAVIS_BUILD_DIR
    - go get -u ./...
    - go test -race -coverprofile coverage.out ./...
    - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - software-properties-common
            - curl
            - zfsutils-linux
      go:
        - 1.13.x
      env:
        - MATRIX_EVAL="GO111MODULE=on"
      script: *script-linux-coverage

before_install:
  - eval "${MATRIX_EVAL}"
